### ISSUE TITLE
Possibility to use signature version v2 for S3 buckets

### ISSUE THREAD

**Issue by bartversluijs** [balena-io/open-balena-registry#113]
Hi,

We're currently using an external S3 provider (DigitalOcean spaces), but we'd like to create a reverse proxy to that bucket so the bucket is also reachable on `s3.<openbalena-hostname>`. However, the v4 signature version uses the request URI in the signature, and the reverse proxy will have a different URI than the bucket itself. When signature version v2 is used, all goes well.

I saw the [v4auth option](https://github.com/balena-io/open-balena-registry/blob/master/config/confd/templates/docker-registry.yml.tmpl#L45) in the template, and I'd like to suggest that there's an environment variable that sets this to false. That way, we can use the reverse proxy in our openBalena environment.

I'd like to create a PR for this (and maybe I will), however, I can't test it properly. But I'll do my best!

Thanks in advance!

**Comment by dfunckt** [comment]
> When signature version v2 is used, all goes well.

How did you confirm this? Making this configurable via the environment is cheap but I'm afraid it won't work -- my memory may be failing me but I think we were actually forced to change to v4 auth in the past.

**Comment by bartversluijs** [comment]
I did confirm this using the S3 SDK. I'm setting up a new openBalena environment as we speak where I'll try to use the proxy as S3 endpoint and setting the v4auth to false and verify if that does the job for the registry!

**Comment by bartversluijs** [comment]
Ah so per the [docs of the Docker registry](https://docs.docker.com/registry/storage-drivers/s3/), if it's set to false, there isn't a default behaviour. So don't really know what that means, but I can confirm it doesn't work when it is set to false.

I'll have to come up with a different solution then, bummer...

**Comment by dfunckt** [comment]
What did you pass to the registry for `COMMON_REGION` while testing @bartversluijs?

**Comment by bartversluijs** [comment]
I've passed the region 'ams3' (DO uses ams3.digitaloceanspaces.com).
I am lacking knowledge about S3, but I'm doing a trial / error with the reverse proxy to the bucket, because (for firewall reasons) I want that the devices in openBalena only communicate to `*.<openbalena-domain>`, and not to the ams3.digitaloceanspaces.com for its images.

**Comment by dfunckt** [comment]
I did some googling to remind myself of the situation and the reason we moved to v4 was because Amazon had announced it would stop accepting v2 by some time in 2019: https://forums.aws.amazon.com/ann.jspa?annID=5816

The docs you linked suggest that setting this to `false` would make the driver use v2 with the caveat that the eu-central-1 region isn't accepting it (possibly other or all regions have since dropped support for v2 as well).

Can you try setting `v4auth: false` *and* `region: NONE` and see if that works?

**Comment by bartversluijs** [comment]
I've just removed my cluster, but I'll try to do that.
I'll also try to find a way to do a reverse proxy with v4 support enabled.

Just for your information, if I set everything to the DO bucket itself (so <bucket-name>.ams3.digitaloceanspaces.com), all works well, even with v4. But v4 doesn't work when using the reverse proxy I've created. So not that you're confused that external S3 buckets don't work, only trying to get v2 to work (and eventually fix the problem with reverse proxy and support v4).

**Comment by dfunckt** [comment]
That's because v4 generates signed URLs that include the host. Did you try with `redirect: false`? Supposedly the registry will stream all data coming from DO through it.

**Comment by bartversluijs** [comment]
If you're telling me that setting redirect to false will fix the problem, you'll be my hero. But I'll try that first!

**Comment by bartversluijs** [comment]
Added the following as stated in the [docs](https://docs.docker.com/registry/configuration/#redirect)
```
redirect:
  disable: true
```

Only thing left to do is find a way to check if this works and it doesn't redirect to the space but stream the data.

**Comment by bartversluijs** [comment]
@dfunckt you're my hero 🎉 
It was a puzzle, but had to set the config you said, and it works now.
However, this isn't an option in the registry using an environment variable, so do I'll create an issue for that.

Nonetheless, thanks!
